### ISSUE TITLE
[Documentation] "Index" links to a 404 page

### ISSUE THREAD

**Issue by ljcooke** [slisne/nodaire#8]
Each page in the documentation has an "Index" link at the top. This leads to a "Page not found" error at: https://slisne.github.io/nodaire/_index.html

The file exists in the repo (in the `gh-pages` branch). Is this something to do with GitHub Pages treating it like a Jekyll site?

**Comment by M4rk9696** [comment]
@ljcooke it does seem like it's treating it as a Jekyll site

https://help.github.com/en/articles/files-that-start-with-an-underscore-are-missing

**Comment by ljcooke** [comment]
@M4rk9696 Thanks, adding a _.nojekyll_ file fixed it!
